site_name: Routing Docs
theme:
  name: readthedocs
markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - def_list

nav:
  - Overview: index.md
  - Quick Start: quick-start.md
  - API Reference:
    - Route Class: routes/index.md
    - Navigation: navigating/index.md
    - Data Loading: data-loading/index.md
    - Caching: caching/index.md